application: hotel
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /www/assets
  static_dir: /www/assets


- url: /(.+)
  static_files: www/\1
  upload: www/(.+)

- url: .*
  script: main.app



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  